import type { DemoWorkspace } from "@/features/demo/types";

/** Deterministic indie demo — labels only, no live GitHub URLs. */
export function getNorthlightAuroraDemo(): DemoWorkspace {
  const lastVisitAt = "2026-08-01T09:00:00.000Z";

  const members = [
    {
      id: "m_code",
      name: "Alex Rivera",
      functionalRole: "Programming",
      availableThisWeek: true,
    },
    {
      id: "m_art",
      name: "Mar Okada",
      functionalRole: "Art",
      availableThisWeek: false,
    },
    {
      id: "m_design",
      name: "Sam Ortega",
      functionalRole: "Design",
      availableThisWeek: true,
    },
    {
      id: "m_script",
      name: "Noa Berg",
      functionalRole: "Writing",
      availableThisWeek: true,
    },
    {
      id: "m_prod",
      name: "Quim Hale",
      functionalRole: "Production",
      availableThisWeek: true,
    },
    {
      id: "m_sound",
      name: "Ivy Chen",
      functionalRole: "Sound",
      availableThisWeek: true,
    },
  ];

  const work = [
    {
      id: "w_portal",
      title: "Player portal shell",
      status: "done" as const,
      priority: "medium" as const,
      assigneeId: "m_code",
      dependsOn: [],
      blocks: [],
      completedSinceVisit: true,
      staleDays: null,
    },
    {
      id: "w_asset",
      title: "Character turnaround asset",
      status: "in_progress" as const,
      priority: "high" as const,
      assigneeId: "m_art",
      dependsOn: [],
      blocks: ["w_integrate", "w_ui", "w_trailer"],
      completedSinceVisit: false,
      staleDays: 5,
    },
    {
      id: "w_integrate",
      title: "Integrate character into build",
      status: "ready" as const,
      priority: "high" as const,
      assigneeId: "m_code",
      dependsOn: ["w_asset"],
      blocks: [],
      completedSinceVisit: false,
      staleDays: null,
    },
    {
      id: "w_ui",
      title: "Character select UI polish",
      status: "ready" as const,
      priority: "medium" as const,
      assigneeId: "m_design",
      dependsOn: ["w_asset"],
      blocks: [],
      completedSinceVisit: false,
      staleDays: null,
    },
    {
      id: "w_trailer",
      title: "Vertical slice trailer stills",
      status: "backlog" as const,
      priority: "medium" as const,
      assigneeId: null,
      dependsOn: ["w_asset"],
      blocks: [],
      completedSinceVisit: false,
      staleDays: null,
    },
    {
      id: "w_critical",
      title: "Save-slot migration for demo build",
      status: "ready" as const,
      priority: "high" as const,
      assigneeId: null,
      dependsOn: [],
      blocks: [],
      completedSinceVisit: false,
      staleDays: 3,
    },
    {
      id: "w_pr",
      title: "Input remapping pull request",
      status: "review" as const,
      priority: "high" as const,
      assigneeId: "m_code",
      dependsOn: [],
      blocks: [],
      completedSinceVisit: false,
      staleDays: 3,
    },
    {
      id: "w_ci",
      title: "CI: lint suite on remapping branch",
      status: "in_progress" as const,
      priority: "high" as const,
      assigneeId: "m_code",
      dependsOn: [],
      blocks: ["w_pr"],
      completedSinceVisit: false,
      staleDays: 1,
    },
  ];

  const signals = [
    {
      id: "s_block",
      type: "work_blocked" as const,
      kind: "fact" as const,
      severity: "high" as const,
      title: "Character asset blocks three work items",
      evidence: "Explicit dependency: integrate, UI, and trailer wait on the asset.",
      whyItMatters: "Nothing downstream can ship until art lands.",
      recommendedAction: "Confirm delivery date with Art or re-scope the slice.",
      occurredAt: "2026-08-02T14:00:00.000Z",
      assigneeLabel: "Mar Okada",
      originLabel: "HubForge dependency",
      originRef: "demo://dependency/w_asset",
      subjectWorkId: "w_asset",
    },
    {
      id: "s_review",
      type: "review_waiting" as const,
      kind: "fact" as const,
      severity: "high" as const,
      title: "Pull request waiting for review",
      evidence: "Input remapping PR open in review for 3 days (demo record).",
      whyItMatters: "Blocks merge of input work for the vertical slice.",
      recommendedAction: "Assign a reviewer who is available this week.",
      occurredAt: "2026-08-01T11:00:00.000Z",
      assigneeLabel: "Alex Rivera",
      originLabel: "Simulated GitHub pull request",
      originRef: "demo://github/pr/42",
      subjectWorkId: "w_pr",
    },
    {
      id: "s_ci",
      type: "ci_failed" as const,
      kind: "fact" as const,
      severity: "high" as const,
      title: "CI failed on remapping branch",
      evidence: "Demo check run: lint suite failed (simulated).",
      whyItMatters: "The PR cannot merge until CI is green.",
      recommendedAction: "Open the failing check and fix lint errors.",
      occurredAt: "2026-08-03T08:30:00.000Z",
      assigneeLabel: "Alex Rivera",
      originLabel: "Simulated GitHub check",
      originRef: "demo://github/check/ci-lint",
      subjectWorkId: "w_ci",
    },
    {
      id: "s_unassigned",
      type: "unassigned_critical" as const,
      kind: "fact" as const,
      severity: "high" as const,
      title: "Critical work has no owner yet",
      evidence: "Save-slot migration is high priority with no assignee.",
      whyItMatters: "Demo build risk if nobody claims it before the milestone.",
      recommendedAction: "Assign Programming or Production to own it.",
      occurredAt: "2026-08-02T16:00:00.000Z",
      assigneeLabel: "Nobody yet",
      originLabel: "HubForge work item",
      originRef: "demo://work/w_critical",
      subjectWorkId: "w_critical",
    },
    {
      id: "s_stale",
      type: "work_stale" as const,
      kind: "inference" as const,
      severity: "medium" as const,
      title: "Asset work may be stalled",
      evidence: "No status change for 5 days while three items wait on it.",
      whyItMatters: "Inference only — confirm with Art before escalating.",
      recommendedAction: "Ask for a status update; do not assume blocked forever.",
      occurredAt: "2026-08-03T10:00:00.000Z",
      assigneeLabel: "Mar Okada",
      originLabel: "HubForge inference",
      originRef: "demo://inference/w_asset-stale",
      subjectWorkId: "w_asset",
    },
    {
      id: "s_done",
      type: "completed_since_visit" as const,
      kind: "fact" as const,
      severity: "low" as const,
      title: "Portal shell completed since your last visit",
      evidence: "Work item marked completed after 2026-08-01T09:00Z.",
      whyItMatters: "Progress landed while you were away.",
      recommendedAction: "Skim the completed item, then focus on blockers.",
      occurredAt: "2026-08-01T18:00:00.000Z",
      assigneeLabel: "Alex Rivera",
      originLabel: "HubForge work item",
      originRef: "demo://work/w_portal",
      subjectWorkId: "w_portal",
    },
  ];

  const dependencies = [
    {
      id: "d1",
      blockedId: "w_integrate",
      blockerId: "w_asset",
      blockedTitle: "Integrate character into build",
      blockerTitle: "Character turnaround asset",
      affectedCount: 3,
      assigneeLabel: "Mar Okada",
      status: "In progress",
      blockedForDays: 5,
      evidence: "Explicit HubForge dependency edge (demo).",
    },
    {
      id: "d2",
      blockedId: "w_ui",
      blockerId: "w_asset",
      blockedTitle: "Character select UI polish",
      blockerTitle: "Character turnaround asset",
      affectedCount: 3,
      assigneeLabel: "Mar Okada",
      status: "In progress",
      blockedForDays: 5,
      evidence: "Explicit HubForge dependency edge (demo).",
    },
    {
      id: "d3",
      blockedId: "w_trailer",
      blockerId: "w_asset",
      blockedTitle: "Vertical slice trailer stills",
      blockerTitle: "Character turnaround asset",
      affectedCount: 3,
      assigneeLabel: "Mar Okada",
      status: "In progress",
      blockedForDays: 5,
      evidence: "Explicit HubForge dependency edge (demo).",
    },
  ];

  return {
    mode: "demo",
    organizationName: "Northlight Studio",
    projectName: "Aurora",
    lastVisitAt,
    members,
    work,
    signals,
    dependencies,
    briefingFacts: [
      "1 work item completed",
      "1 blocker still holding three items",
      "1 pull request waiting for review",
      "1 simulated CI failure",
    ],
  };
}
