name: Solicitud de funcionalidad
description: Proponer una mejora de producto
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema
      description: ¿Qué problema de usuario resuelve esto?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Propuesta
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Fuera de alcance
